var x = 10

console.log(x)
console.log(x)
console.log(x)
console.log(x)
console.log(x)

//loop
for (var i = 0; i<5; i++) {
console.log(x)
}

var z = 7
for (var i = 0; i<=500; i++) {
    console.log(z)
    console.log(i)
}
 var m = 6
 for (var i = 0; i<10; i++){
    console.log(m)
 }
var a = 8 
for (var i = 4; i<10; i++) {
console.log(a)
}

for (var i = 1; i<=10; i++){
    console.log(i)
}
//while loop
var ai = 1;
while(ai < 10 ) {
    console.log(ai);
    ai = ai + 1;
}